<?php

namespace Database\Seeders;

use App\Models\Cluster;
use App\Models\Pillar;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClusterSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('clusters')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $clusters = [

            // ── Pillar 1: home-electrician-kuwait ──────────────────────────
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'رقم كهربائي منازل الكويت', 'en' => 'Home Electrician Number Kuwait'],
                'slug'        => ['ar' => 'رقم-كهربائي-منازل-الكويت', 'en' => 'home-electrician-number-kuwait'],
                'meta_title'  => ['ar' => 'رقم كهربائي منازل الكويت | إلكتريك كويت', 'en' => 'Home Electrician Number Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'اتصل بكهربائي منازل معتمد في الكويت. خدمة سريعة وأسعار مناسبة في جميع المناطق.', 'en' => 'Call a certified home electrician in Kuwait. Fast service and competitive prices across all areas.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نوفر أرقام كهربائي منازل موثوقة في الكويت لجميع أعمال الكهرباء المنزلية.</p><ul><li>فنيون معتمدون</li><li>أسعار شفافة</li><li>خدمة سريعة</li></ul>', 'en' => '<p>We provide trusted home electrician numbers in Kuwait for all residential electrical work.</p><ul><li>Certified technicians</li><li>Transparent pricing</li><li>Fast response</li></ul>'],
                'search_intent' => 'informational',
                'status'      => 'active',
                'sort_order'  => 1,
            ],
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'كهربائي قريب مني الكويت', 'en' => 'Electrician Near Me Kuwait'],
                'slug'        => ['ar' => 'كهربائي-قريب-مني-الكويت', 'en' => 'electrician-near-me-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي قريب مني في الكويت | إلكتريك كويت', 'en' => 'Electrician Near Me Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'ابحث عن كهربائي قريب منك في الكويت. نصل إليك في أسرع وقت ممكن.', 'en' => 'Find an electrician near you in Kuwait. We reach you as quickly as possible.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>كهربائي قريب منك في جميع مناطق الكويت. نصل إليك خلال ساعة.</p><ul><li>تغطية كاملة لجميع المناطق</li><li>وقت استجابة سريع</li><li>فنيون محترفون</li></ul>', 'en' => '<p>Electrician near you in all Kuwait areas. We reach you within an hour.</p><ul><li>Full area coverage</li><li>Fast response time</li><li>Professional technicians</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 2,
            ],
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'أفضل كهربائي في الكويت', 'en' => 'Best Electrician in Kuwait'],
                'slug'        => ['ar' => 'افضل-كهربائي-في-الكويت', 'en' => 'best-electrician-in-kuwait'],
                'meta_title'  => ['ar' => 'أفضل كهربائي في الكويت | إلكتريك كويت', 'en' => 'Best Electrician in Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'اعثر على أفضل كهربائي معتمد في الكويت. خبرة واسعة وضمان على جميع الأعمال.', 'en' => 'Find the best certified electrician in Kuwait. Wide experience and warranty on all work.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم أفضل خدمات كهرباء في الكويت مع ضمان على جميع الأعمال المنجزة.</p><ul><li>خبرة أكثر من 10 سنوات</li><li>ضمان شامل</li><li>تقييمات ممتازة</li></ul>', 'en' => '<p>We provide the best electrical services in Kuwait with warranty on all completed work.</p><ul><li>Over 10 years experience</li><li>Comprehensive warranty</li><li>Excellent reviews</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 3,
            ],
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'كهربائي 24 ساعة الكويت', 'en' => '24 Hour Electrician Kuwait'],
                'slug'        => ['ar' => 'كهربائي-24-ساعة-الكويت', 'en' => '24-hour-electrician-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي 24 ساعة الكويت | إلكتريك كويت', 'en' => '24 Hour Electrician Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'كهربائي متاح 24 ساعة في الكويت. خدمة طارئة على مدار الساعة طوال أيام الأسبوع.', 'en' => 'Electrician available 24 hours in Kuwait. Emergency service around the clock, 7 days a week.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>خدمة كهربائي متاحة 24 ساعة يومياً في جميع أنحاء الكويت للحالات الطارئة.</p><ul><li>متاح على مدار الساعة</li><li>فريق جاهز للتدخل السريع</li><li>لا رسوم إضافية ليلية</li></ul>', 'en' => '<p>24-hour electrician service available across Kuwait for emergency situations.</p><ul><li>Available around the clock</li><li>Team ready for rapid response</li><li>No extra night charges</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 4,
            ],
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'كهربائي شقق الكويت', 'en' => 'Apartment Electrician Kuwait'],
                'slug'        => ['ar' => 'كهربائي-شقق-الكويت', 'en' => 'apartment-electrician-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي شقق الكويت | إلكتريك كويت', 'en' => 'Apartment Electrician Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'كهربائي متخصص في صيانة وتركيب كهرباء الشقق في الكويت. أسعار مناسبة.', 'en' => 'Electrician specialized in apartment electrical maintenance and installation in Kuwait.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>خدمات كهرباء متخصصة للشقق السكنية في الكويت. صيانة وتركيب باحترافية.</p><ul><li>خبرة في أنظمة الشقق</li><li>أسعار مناسبة</li><li>أعمال نظيفة ومرتبة</li></ul>', 'en' => '<p>Specialized electrical services for residential apartments in Kuwait.</p><ul><li>Experience with apartment systems</li><li>Competitive prices</li><li>Clean and tidy work</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 5,
            ],
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'كهربائي مجمعات سكنية الكويت', 'en' => 'Residential Complex Electrician Kuwait'],
                'slug'        => ['ar' => 'كهربائي-مجمعات-سكنية-الكويت', 'en' => 'residential-complex-electrician-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي مجمعات سكنية | إلكتريك كويت', 'en' => 'Residential Complex Electrician Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'خدمات كهرباء متكاملة للمجمعات السكنية في الكويت. عقود صيانة دورية.', 'en' => 'Complete electrical services for residential complexes in Kuwait. Periodic maintenance contracts.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم خدمات كهرباء شاملة للمجمعات السكنية في الكويت مع عقود صيانة دورية.</p><ul><li>فرق متخصصة</li><li>عقود صيانة</li><li>متابعة مستمرة</li></ul>', 'en' => '<p>We provide comprehensive electrical services for residential complexes in Kuwait with periodic maintenance contracts.</p><ul><li>Specialized teams</li><li>Maintenance contracts</li><li>Continuous follow-up</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 6,
            ],
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'كهربائي رخيص الكويت', 'en' => 'Cheap Electrician Kuwait'],
                'slug'        => ['ar' => 'كهربائي-رخيص-الكويت', 'en' => 'cheap-electrician-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي رخيص في الكويت | إلكتريك كويت', 'en' => 'Cheap Electrician Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'كهربائي بأسعار مناسبة في الكويت. جودة عالية بأقل تكلفة ممكنة.', 'en' => 'Electrician at affordable prices in Kuwait. High quality at the lowest possible cost.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>خدمات كهربائية بأسعار تنافسية في الكويت مع الحفاظ على أعلى معايير الجودة.</p><ul><li>أسعار شفافة</li><li>لا تكاليف خفية</li><li>أفضل قيمة مقابل المال</li></ul>', 'en' => '<p>Electrical services at competitive prices in Kuwait while maintaining the highest quality standards.</p><ul><li>Transparent pricing</li><li>No hidden costs</li><li>Best value for money</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 7,
            ],
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'أسعار الكهربائي في الكويت', 'en' => 'Electrician Prices in Kuwait'],
                'slug'        => ['ar' => 'اسعار-الكهربائي-في-الكويت', 'en' => 'electrician-prices-in-kuwait'],
                'meta_title'  => ['ar' => 'أسعار الكهربائي في الكويت | إلكتريك كويت', 'en' => 'Electrician Prices in Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تعرف على أسعار خدمات الكهربائي في الكويت. أسعار واضحة وشفافة بدون مفاجآت.', 'en' => 'Learn about electrician service prices in Kuwait. Clear and transparent pricing with no surprises.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم أسعاراً واضحة وشفافة لجميع خدمات الكهرباء في الكويت.</p><ul><li>عروض أسعار مجانية</li><li>أسعار ثابتة</li><li>لا رسوم خفية</li></ul>', 'en' => '<p>We offer clear and transparent prices for all electrical services in Kuwait.</p><ul><li>Free quotes</li><li>Fixed prices</li><li>No hidden fees</li></ul>'],
                'search_intent' => 'informational',
                'status'      => 'active',
                'sort_order'  => 8,
            ],
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'صيانة كهرباء المنازل القديمة', 'en' => 'Old Home Electrical Maintenance Kuwait'],
                'slug'        => ['ar' => 'صيانة-كهرباء-المنازل-القديمة', 'en' => 'old-home-electrical-maintenance-kuwait'],
                'meta_title'  => ['ar' => 'صيانة كهرباء المنازل القديمة | إلكتريك كويت', 'en' => 'Old Home Electrical Maintenance Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'متخصصون في صيانة وتحديث الأنظمة الكهربائية في المنازل القديمة بالكويت.', 'en' => 'Specialists in maintaining and upgrading electrical systems in old homes in Kuwait.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>خدمات متخصصة لصيانة وتطوير الأنظمة الكهربائية في المنازل القديمة بالكويت.</p><ul><li>تحديث الأسلاك القديمة</li><li>استبدال اللوحات التالفة</li><li>تأمين المنزل كهربائياً</li></ul>', 'en' => '<p>Specialized services for maintaining and upgrading electrical systems in old homes in Kuwait.</p><ul><li>Updating old wiring</li><li>Replacing damaged panels</li><li>Electrical home safety</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 9,
            ],
            [
                'pillar_slug' => 'home-electrician-kuwait',
                'title'       => ['ar' => 'فحص كهرباء المنازل الكويت', 'en' => 'Home Electrical Inspection Kuwait'],
                'slug'        => ['ar' => 'فحص-كهرباء-المنازل-الكويت', 'en' => 'home-electrical-inspection-kuwait'],
                'meta_title'  => ['ar' => 'فحص كهرباء المنازل الكويت | إلكتريك كويت', 'en' => 'Home Electrical Inspection Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'خدمة فحص شامل لكهرباء المنازل في الكويت. اكتشف الأعطال قبل أن تتفاقم.', 'en' => 'Comprehensive home electrical inspection service in Kuwait. Detect faults before they worsen.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم خدمة فحص شاملة لكهرباء منزلك في الكويت لاكتشاف الأعطال مبكراً.</p><ul><li>فحص دقيق لجميع النقاط</li><li>تقرير مفصل</li><li>توصيات للصيانة</li></ul>', 'en' => '<p>We provide a comprehensive electrical inspection service for your home in Kuwait to detect faults early.</p><ul><li>Accurate inspection of all points</li><li>Detailed report</li><li>Maintenance recommendations</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 10,
            ],

            // ── Pillar 2: electrical-fault-repair-maintenance-kuwait ───────
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'كشف ماس كهربائي الكويت', 'en' => 'Electrical Short Circuit Detection Kuwait'],
                'slug'        => ['ar' => 'كشف-ماس-كهربائي-الكويت', 'en' => 'electrical-short-circuit-detection-kuwait'],
                'meta_title'  => ['ar' => 'كشف ماس كهربائي الكويت | إلكتريك كويت', 'en' => 'Electrical Short Circuit Detection Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'خدمة كشف الماس الكهربائي باستخدام أحدث الأجهزة في الكويت. سرعة وأمان.', 'en' => 'Short circuit detection service using the latest equipment in Kuwait. Speed and safety.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نكشف عن الماس الكهربائي باستخدام أجهزة متطورة لضمان سلامة منزلك.</p><ul><li>كشف دقيق</li><li>إصلاح فوري</li><li>ضمان السلامة</li></ul>', 'en' => '<p>We detect electrical short circuits using advanced equipment to ensure your home safety.</p><ul><li>Accurate detection</li><li>Immediate repair</li><li>Safety guarantee</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 1,
            ],
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'إصلاح انقطاع الكهرباء الكويت', 'en' => 'Power Outage Repair Kuwait'],
                'slug'        => ['ar' => 'إصلاح-انقطاع-الكهرباء-الكويت', 'en' => 'power-outage-repair-kuwait'],
                'meta_title'  => ['ar' => 'إصلاح انقطاع الكهرباء الكويت | إلكتريك كويت', 'en' => 'Power Outage Repair Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'إصلاح انقطاع الكهرباء بسرعة في الكويت. فريق متخصص يصل إليك خلال ساعة.', 'en' => 'Fast power outage repair in Kuwait. Specialized team reaches you within an hour.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نصلح انقطاع الكهرباء بسرعة وكفاءة في جميع مناطق الكويت.</p><ul><li>تشخيص سريع</li><li>إصلاح فوري</li><li>خدمة طارئة</li></ul>', 'en' => '<p>We repair power outages quickly and efficiently across all Kuwait areas.</p><ul><li>Fast diagnosis</li><li>Immediate repair</li><li>Emergency service</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 2,
            ],
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'القاطع يفصل باستمرار الكويت', 'en' => 'Circuit Breaker Keeps Tripping Kuwait'],
                'slug'        => ['ar' => 'القاطع-يفصل-باستمرار-الكويت', 'en' => 'circuit-breaker-keeps-tripping-kuwait'],
                'meta_title'  => ['ar' => 'القاطع يفصل باستمرار الكويت | إلكتريك كويت', 'en' => 'Circuit Breaker Keeps Tripping Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'حل مشكلة القاطع الذي يفصل باستمرار في منزلك بالكويت. تشخيص وإصلاح احترافي.', 'en' => 'Solve the circuit breaker tripping problem in your Kuwait home. Professional diagnosis and repair.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نشخص ونصلح مشكلة القاطع الذي يفصل باستمرار لضمان سلامة منزلك.</p><ul><li>تشخيص السبب الجذري</li><li>إصلاح دائم</li><li>فحص كامل للنظام</li></ul>', 'en' => '<p>We diagnose and fix the circuit breaker tripping issue to ensure your home safety.</p><ul><li>Root cause diagnosis</li><li>Permanent fix</li><li>Full system check</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 3,
            ],
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'إصلاح احتراق الأسلاك الكويت', 'en' => 'Burnt Wire Repair Kuwait'],
                'slug'        => ['ar' => 'إصلاح-احتراق-الأسلاك-الكويت', 'en' => 'burnt-wire-repair-kuwait'],
                'meta_title'  => ['ar' => 'إصلاح احتراق الأسلاك الكويت | إلكتريك كويت', 'en' => 'Burnt Wire Repair Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'إصلاح الأسلاك المحترقة في الكويت بأمان واحترافية. خدمة طارئة متاحة.', 'en' => 'Safe and professional burnt wire repair in Kuwait. Emergency service available.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>إصلاح الأسلاك المحترقة بأمان واحترافية لحماية منزلك من الحرائق.</p><ul><li>إصلاح آمن</li><li>استبدال الأسلاك التالفة</li><li>فحص شامل</li></ul>', 'en' => '<p>Safe and professional burnt wire repair to protect your home from fires.</p><ul><li>Safe repair</li><li>Replacement of damaged wires</li><li>Comprehensive inspection</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 4,
            ],
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'ضعف الكهرباء في المنزل الكويت', 'en' => 'Weak Electricity at Home Kuwait'],
                'slug'        => ['ar' => 'ضعف-الكهرباء-في-المنزل-الكويت', 'en' => 'weak-electricity-home-kuwait'],
                'meta_title'  => ['ar' => 'ضعف الكهرباء في المنزل الكويت | إلكتريك كويت', 'en' => 'Weak Electricity at Home Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'حل مشكلة ضعف التيار الكهربائي في منزلك بالكويت. فنيون متخصصون لتشخيص الأعطال.', 'en' => 'Solve weak electrical current issues in your Kuwait home. Specialized technicians to diagnose faults.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نشخص ونصلح مشاكل ضعف التيار الكهربائي في المنازل والشقق بالكويت.</p><ul><li>قياس الجهد</li><li>تشخيص المشكلة</li><li>حل دائم</li></ul>', 'en' => '<p>We diagnose and fix weak electrical current issues in homes and apartments in Kuwait.</p><ul><li>Voltage measurement</li><li>Problem diagnosis</li><li>Permanent solution</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 5,
            ],
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'رائحة احتراق من الكهرباء الكويت', 'en' => 'Burning Smell from Electrical Kuwait'],
                'slug'        => ['ar' => 'رائحة-احتراق-من-الكهرباء-الكويت', 'en' => 'burning-smell-electrical-kuwait'],
                'meta_title'  => ['ar' => 'رائحة احتراق من الكهرباء الكويت | إلكتريك كويت', 'en' => 'Burning Smell from Electrical Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'رائحة احتراق من الأسلاك؟ اتصل بنا فوراً. خدمة طارئة 24 ساعة في الكويت.', 'en' => 'Burning smell from wires? Call us immediately. 24-hour emergency service in Kuwait.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>رائحة الاحتراق من الكهرباء خطر جدي. نصل إليك فوراً لفحص المشكلة.</p><ul><li>استجابة طارئة</li><li>فحص شامل</li><li>إصلاح آمن</li></ul>', 'en' => '<p>Burning smell from electricity is a serious danger. We reach you immediately to inspect the problem.</p><ul><li>Emergency response</li><li>Comprehensive check</li><li>Safe repair</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 6,
            ],
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'شرارة من المفتاح الكهربائي الكويت', 'en' => 'Sparking Electrical Switch Kuwait'],
                'slug'        => ['ar' => 'شرارة-من-المفتاح-الكهربائي-الكويت', 'en' => 'sparking-electrical-switch-kuwait'],
                'meta_title'  => ['ar' => 'شرارة من المفتاح الكهربائي الكويت | إلكتريك كويت', 'en' => 'Sparking Electrical Switch Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'مفتاح كهرباء يُصدر شرارة؟ خطر جسيم. اتصل بنا الآن للإصلاح الفوري في الكويت.', 'en' => 'Electrical switch sparking? Serious hazard. Call us now for immediate repair in Kuwait.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>الشرارة من المفاتيح الكهربائية خطر يستوجب تدخلاً فورياً لحماية منزلك.</p><ul><li>استجابة فورية</li><li>استبدال المفاتيح التالفة</li><li>فحص الأسلاك</li></ul>', 'en' => '<p>Sparking from electrical switches requires immediate intervention to protect your home.</p><ul><li>Immediate response</li><li>Replacement of damaged switches</li><li>Wire inspection</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 7,
            ],
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'الكهرباء تفصل عند المكيف الكويت', 'en' => 'Power Trips When AC On Kuwait'],
                'slug'        => ['ar' => 'الكهرباء-تفصل-عند-المكيف-الكويت', 'en' => 'power-trips-when-ac-on-kuwait'],
                'meta_title'  => ['ar' => 'الكهرباء تفصل عند المكيف الكويت | إلكتريك كويت', 'en' => 'Power Trips When AC On Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'الكهرباء تنقطع عند تشغيل المكيف؟ حل المشكلة من إلكتريك كويت.', 'en' => 'Power cuts when you turn on the AC? Solve the problem with ElectricQ8.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نحل مشكلة انقطاع الكهرباء عند تشغيل المكيف بفحص الأحمال وتحديث اللوحة.</p><ul><li>فحص الأحمال الكهربائية</li><li>ترقية اللوحة الكهربائية</li><li>توزيع صحيح للأحمال</li></ul>', 'en' => '<p>We solve the power cut issue when the AC turns on by checking loads and upgrading the panel.</p><ul><li>Electrical load check</li><li>Panel upgrade</li><li>Proper load distribution</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 8,
            ],
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'ارتفاع الأحمال الكهربائية الكويت', 'en' => 'High Electrical Load Kuwait'],
                'slug'        => ['ar' => 'ارتفاع-الأحمال-الكهربائية-الكويت', 'en' => 'high-electrical-load-kuwait'],
                'meta_title'  => ['ar' => 'ارتفاع الأحمال الكهربائية الكويت | إلكتريك كويت', 'en' => 'High Electrical Load Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'حل مشكلة ارتفاع الأحمال الكهربائية وتوزيعها بشكل صحيح في الكويت.', 'en' => 'Solve high electrical load problems and distribute them properly in Kuwait.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نفحص ونوزع الأحمال الكهربائية بشكل صحيح لمنع الأعطال والحوادث.</p><ul><li>قياس الأحمال</li><li>إعادة التوزيع</li><li>تحديث اللوحة</li></ul>', 'en' => '<p>We inspect and distribute electrical loads properly to prevent faults and accidents.</p><ul><li>Load measurement</li><li>Redistribution</li><li>Panel update</li></ul>'],
                'search_intent' => 'informational',
                'status'      => 'active',
                'sort_order'  => 9,
            ],
            [
                'pillar_slug' => 'electrical-fault-repair-maintenance-kuwait',
                'title'       => ['ar' => 'فحص الأعطال الكهربائية المنزلية الكويت', 'en' => 'Home Electrical Fault Inspection Kuwait'],
                'slug'        => ['ar' => 'فحص-الأعطال-الكهربائية-المنزلية-الكويت', 'en' => 'home-electrical-fault-inspection-kuwait'],
                'meta_title'  => ['ar' => 'فحص الأعطال الكهربائية المنزلية الكويت | إلكتريك كويت', 'en' => 'Home Electrical Fault Inspection Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'فحص شامل للأعطال الكهربائية في منزلك بالكويت. تقرير مفصل وإصلاح احترافي.', 'en' => 'Comprehensive electrical fault inspection for your Kuwait home. Detailed report and professional repair.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>فحص شامل لجميع الأعطال الكهربائية في منزلك مع تقرير مفصل وخطة إصلاح.</p><ul><li>فحص شامل</li><li>تقرير مفصل</li><li>خطة إصلاح واضحة</li></ul>', 'en' => '<p>Comprehensive inspection of all electrical faults in your home with a detailed report and repair plan.</p><ul><li>Comprehensive inspection</li><li>Detailed report</li><li>Clear repair plan</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 10,
            ],

            // ── Pillar 3: electrical-installation-wiring-kuwait ───────────
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'تأسيس كهرباء منزل جديد الكويت', 'en' => 'New Home Electrical Installation Kuwait'],
                'slug'        => ['ar' => 'تأسيس-كهرباء-منزل-جديد-الكويت', 'en' => 'new-home-electrical-installation-kuwait'],
                'meta_title'  => ['ar' => 'تأسيس كهرباء منزل جديد الكويت | إلكتريك كويت', 'en' => 'New Home Electrical Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تأسيس كهرباء منزلك الجديد في الكويت وفق أعلى المواصفات والمعايير.', 'en' => 'New home electrical installation in Kuwait to the highest specifications and standards.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقوم بتأسيس الكهرباء في منزلك الجديد وفق أحدث المواصفات الكويتية.</p><ul><li>مواصفات معتمدة</li><li>أسلاك عالية الجودة</li><li>ضمان شامل</li></ul>', 'en' => '<p>We install electricity in your new home according to the latest Kuwaiti specifications.</p><ul><li>Approved specifications</li><li>High-quality wires</li><li>Comprehensive warranty</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 1,
            ],
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'تأسيس كهرباء فلل الكويت', 'en' => 'Villa Electrical Installation Kuwait'],
                'slug'        => ['ar' => 'تأسيس-كهرباء-فلل-الكويت', 'en' => 'villa-electrical-installation-kuwait'],
                'meta_title'  => ['ar' => 'تأسيس كهرباء فلل الكويت | إلكتريك كويت', 'en' => 'Villa Electrical Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تأسيس كهرباء الفلل في الكويت. فرق متخصصة لإنجاز العمل باحترافية وسرعة.', 'en' => 'Villa electrical installation in Kuwait. Specialized teams for professional and fast completion.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نتخصص في تأسيس الكهرباء للفلل الكويتية بأعلى معايير الجودة والسلامة.</p><ul><li>تأسيس شامل</li><li>أنظمة ذكية</li><li>ضمان 5 سنوات</li></ul>', 'en' => '<p>We specialize in electrical installation for Kuwaiti villas to the highest quality and safety standards.</p><ul><li>Complete installation</li><li>Smart systems</li><li>5-year warranty</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 2,
            ],
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'تمديد كهرباء شقة جديدة الكويت', 'en' => 'New Apartment Wiring Kuwait'],
                'slug'        => ['ar' => 'تمديد-كهرباء-شقة-جديدة-الكويت', 'en' => 'new-apartment-wiring-kuwait'],
                'meta_title'  => ['ar' => 'تمديد كهرباء شقة جديدة الكويت | إلكتريك كويت', 'en' => 'New Apartment Wiring Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تمديد الكهرباء لشقتك الجديدة في الكويت. عمل احترافي ومرتب بأسعار مناسبة.', 'en' => 'Electrical wiring for your new apartment in Kuwait. Professional and tidy work at competitive prices.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نمدد الكهرباء في شقتك الجديدة بدقة واحترافية وفق مخططات هندسية معتمدة.</p><ul><li>مخططات معتمدة</li><li>عمل نظيف</li><li>أسعار مناسبة</li></ul>', 'en' => '<p>We wire your new apartment with precision and professionalism according to approved engineering plans.</p><ul><li>Approved plans</li><li>Clean work</li><li>Competitive prices</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 3,
            ],
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'تمديد كهرباء ملحق خارجي الكويت', 'en' => 'Outdoor Extension Electrical Wiring Kuwait'],
                'slug'        => ['ar' => 'تمديد-كهرباء-ملحق-خارجي-الكويت', 'en' => 'outdoor-extension-electrical-wiring-kuwait'],
                'meta_title'  => ['ar' => 'تمديد كهرباء ملحق خارجي الكويت | إلكتريك كويت', 'en' => 'Outdoor Extension Electrical Wiring Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تمديد كهرباء الملحق الخارجي في الكويت. توصيل آمن ومطابق للمعايير.', 'en' => 'Outdoor extension electrical wiring in Kuwait. Safe connection meeting all standards.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نمدد كهرباء الملاحق الخارجية بأمان مع مراعاة العوامل البيئية الكويتية.</p><ul><li>كابلات مقاومة للحرارة</li><li>حماية من الأمطار</li><li>معايير السلامة</li></ul>', 'en' => '<p>We wire outdoor extensions safely considering Kuwait environmental factors.</p><ul><li>Heat-resistant cables</li><li>Rain protection</li><li>Safety standards</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 4,
            ],
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'تمديد كهرباء المطبخ الكويت', 'en' => 'Kitchen Electrical Wiring Kuwait'],
                'slug'        => ['ar' => 'تمديد-كهرباء-المطبخ-الكويت', 'en' => 'kitchen-electrical-wiring-kuwait'],
                'meta_title'  => ['ar' => 'تمديد كهرباء المطبخ الكويت | إلكتريك كويت', 'en' => 'Kitchen Electrical Wiring Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تمديد كهرباء المطبخ في الكويت. نقاط طاقة إضافية لجميع الأجهزة المنزلية.', 'en' => 'Kitchen electrical wiring in Kuwait. Additional power points for all home appliances.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نمدد كهرباء المطبخ بنقاط طاقة كافية لجميع الأجهزة المنزلية بأمان.</p><ul><li>نقاط طاقة إضافية</li><li>قواطع متخصصة</li><li>سلامة من الحريق</li></ul>', 'en' => '<p>We wire kitchen electricity with sufficient power points for all home appliances safely.</p><ul><li>Additional power points</li><li>Specialized breakers</li><li>Fire safety</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 5,
            ],
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'تمديد كهرباء الحمامات الكويت', 'en' => 'Bathroom Electrical Wiring Kuwait'],
                'slug'        => ['ar' => 'تمديد-كهرباء-الحمامات-الكويت', 'en' => 'bathroom-electrical-wiring-kuwait'],
                'meta_title'  => ['ar' => 'تمديد كهرباء الحمامات الكويت | إلكتريك كويت', 'en' => 'Bathroom Electrical Wiring Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تمديد كهرباء الحمامات بأمان في الكويت. حماية من الرطوبة والصدمات الكهربائية.', 'en' => 'Safe bathroom electrical wiring in Kuwait. Protection from moisture and electric shocks.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نمدد كهرباء الحمامات بمواصفات خاصة تحمي من الرطوبة والصدمات الكهربائية.</p><ul><li>حماية IP67</li><li>قواطع RCCB</li><li>مواد مقاومة للرطوبة</li></ul>', 'en' => '<p>We wire bathrooms with special specifications protecting from moisture and electric shocks.</p><ul><li>IP67 protection</li><li>RCCB breakers</li><li>Moisture-resistant materials</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 6,
            ],
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'تمديد ثلاث فاز الكويت', 'en' => 'Three Phase Wiring Kuwait'],
                'slug'        => ['ar' => 'تمديد-ثلاث-فاز-الكويت', 'en' => 'three-phase-wiring-kuwait'],
                'meta_title'  => ['ar' => 'تمديد ثلاث فاز الكويت | إلكتريك كويت', 'en' => 'Three Phase Wiring Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تمديد وتركيب ثلاث فاز في الكويت للمنازل والشركات. فنيون معتمدون.', 'en' => 'Three phase wiring and installation in Kuwait for homes and companies. Certified technicians.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقوم بتمديد وتركيب أنظمة ثلاث فاز للمنازل الكبيرة والمنشآت التجارية.</p><ul><li>فنيون معتمدون</li><li>أجهزة قياس دقيقة</li><li>توازن الأوجه</li></ul>', 'en' => '<p>We install three-phase systems for large homes and commercial establishments.</p><ul><li>Certified technicians</li><li>Precise measuring devices</li><li>Phase balancing</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 7,
            ],
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'تمديد كابلات كهربائية الكويت', 'en' => 'Electrical Cable Installation Kuwait'],
                'slug'        => ['ar' => 'تمديد-كابلات-كهربائية-الكويت', 'en' => 'electrical-cable-installation-kuwait'],
                'meta_title'  => ['ar' => 'تمديد كابلات كهربائية الكويت | إلكتريك كويت', 'en' => 'Electrical Cable Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تمديد الكابلات الكهربائية في الكويت للمشاريع الصغيرة والكبيرة.', 'en' => 'Electrical cable installation in Kuwait for small and large projects.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نمدد الكابلات الكهربائية لجميع أنواع المشاريع بأعلى معايير الجودة والسلامة.</p><ul><li>كابلات معتمدة</li><li>تمديد نظيف</li><li>ضمان الجودة</li></ul>', 'en' => '<p>We install electrical cables for all types of projects to the highest quality and safety standards.</p><ul><li>Approved cables</li><li>Clean installation</li><li>Quality guarantee</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 8,
            ],
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'مخطط توزيع كهرباء الكويت', 'en' => 'Electrical Distribution Plan Kuwait'],
                'slug'        => ['ar' => 'مخطط-توزيع-كهرباء-الكويت', 'en' => 'electrical-distribution-plan-kuwait'],
                'meta_title'  => ['ar' => 'مخطط توزيع كهرباء الكويت | إلكتريك كويت', 'en' => 'Electrical Distribution Plan Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'إعداد مخططات توزيع الكهرباء للمنازل والمباني في الكويت. هندسة معتمدة.', 'en' => 'Electrical distribution plans for homes and buildings in Kuwait. Certified engineering.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نعد مخططات توزيع كهربائية دقيقة للمنازل والمباني وفق المعايير الكويتية.</p><ul><li>مخططات هندسية معتمدة</li><li>توزيع مثالي</li><li>كفاءة طاقة عالية</li></ul>', 'en' => '<p>We prepare precise electrical distribution plans for homes and buildings according to Kuwaiti standards.</p><ul><li>Certified engineering plans</li><li>Optimal distribution</li><li>High energy efficiency</li></ul>'],
                'search_intent' => 'informational',
                'status'      => 'active',
                'sort_order'  => 9,
            ],
            [
                'pillar_slug' => 'electrical-installation-wiring-kuwait',
                'title'       => ['ar' => 'تكلفة تأسيس الكهرباء في الكويت', 'en' => 'Electrical Installation Cost Kuwait'],
                'slug'        => ['ar' => 'تكلفة-تأسيس-الكهرباء-في-الكويت', 'en' => 'electrical-installation-cost-kuwait'],
                'meta_title'  => ['ar' => 'تكلفة تأسيس الكهرباء في الكويت | إلكتريك كويت', 'en' => 'Electrical Installation Cost Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تعرف على تكاليف تأسيس الكهرباء في الكويت. أسعار شفافة وعروض مجانية.', 'en' => 'Learn about electrical installation costs in Kuwait. Transparent prices and free quotes.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم أسعاراً شفافة لتأسيس الكهرباء مع عروض أسعار مجانية لمشروعك.</p><ul><li>عروض مجانية</li><li>أسعار تنافسية</li><li>جودة مضمونة</li></ul>', 'en' => '<p>We provide transparent prices for electrical installation with free quotes for your project.</p><ul><li>Free quotes</li><li>Competitive prices</li><li>Guaranteed quality</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 10,
            ],

            // ── Pillar 4: electrical-panels-circuit-breakers-kuwait ───────
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'تركيب لوحة كهربائية جديدة الكويت', 'en' => 'New Electrical Panel Installation Kuwait'],
                'slug'        => ['ar' => 'تركيب-لوحة-كهربائية-جديدة-الكويت', 'en' => 'new-electrical-panel-installation-kuwait'],
                'meta_title'  => ['ar' => 'تركيب لوحة كهربائية جديدة الكويت | إلكتريك كويت', 'en' => 'New Electrical Panel Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب لوحة كهربائية جديدة في الكويت. فنيون معتمدون وضمان على العمل.', 'en' => 'New electrical panel installation in Kuwait. Certified technicians with work warranty.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نركب اللوحات الكهربائية الجديدة بأعلى معايير السلامة في الكويت.</p><ul><li>لوحات معتمدة</li><li>تركيب احترافي</li><li>ضمان شامل</li></ul>', 'en' => '<p>We install new electrical panels to the highest safety standards in Kuwait.</p><ul><li>Approved panels</li><li>Professional installation</li><li>Comprehensive warranty</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 1,
            ],
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'صيانة لوحة الكهرباء الكويت', 'en' => 'Electrical Panel Maintenance Kuwait'],
                'slug'        => ['ar' => 'صيانة-لوحة-الكهرباء-الكويت', 'en' => 'electrical-panel-maintenance-kuwait'],
                'meta_title'  => ['ar' => 'صيانة لوحة الكهرباء الكويت | إلكتريك كويت', 'en' => 'Electrical Panel Maintenance Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'صيانة لوحة الكهرباء في الكويت. فحص دوري وإصلاح احترافي للوحات الكهربائية.', 'en' => 'Electrical panel maintenance in Kuwait. Periodic inspection and professional repair of electrical panels.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم خدمات صيانة دورية للوحات الكهربائية للحفاظ على سلامة منزلك.</p><ul><li>فحص دوري</li><li>إحكام الاتصالات</li><li>اختبار القواطع</li></ul>', 'en' => '<p>We provide periodic maintenance services for electrical panels to maintain your home safety.</p><ul><li>Periodic inspection</li><li>Tightening connections</li><li>Breaker testing</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 2,
            ],
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'تبديل لوحة كهرباء قديمة الكويت', 'en' => 'Old Electrical Panel Replacement Kuwait'],
                'slug'        => ['ar' => 'تبديل-لوحة-كهرباء-قديمة-الكويت', 'en' => 'old-electrical-panel-replacement-kuwait'],
                'meta_title'  => ['ar' => 'تبديل لوحة كهرباء قديمة الكويت | إلكتريك كويت', 'en' => 'Old Electrical Panel Replacement Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تبديل اللوحات الكهربائية القديمة في الكويت بلوحات حديثة آمنة ومطورة.', 'en' => 'Replace old electrical panels in Kuwait with modern, safe, and upgraded panels.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نستبدل اللوحات الكهربائية القديمة بلوحات حديثة آمنة وموفرة للطاقة.</p><ul><li>لوحات حديثة</li><li>استبدال آمن</li><li>كفاءة طاقة</li></ul>', 'en' => '<p>We replace old electrical panels with modern, safe, and energy-efficient panels.</p><ul><li>Modern panels</li><li>Safe replacement</li><li>Energy efficiency</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 3,
            ],
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'تركيب قاطع رئيسي الكويت', 'en' => 'Main Circuit Breaker Installation Kuwait'],
                'slug'        => ['ar' => 'تركيب-قاطع-رئيسي-الكويت', 'en' => 'main-circuit-breaker-installation-kuwait'],
                'meta_title'  => ['ar' => 'تركيب قاطع رئيسي الكويت | إلكتريك كويت', 'en' => 'Main Circuit Breaker Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب القاطع الرئيسي للكهرباء في الكويت. حماية منزلك من الأحمال الزائدة.', 'en' => 'Main circuit breaker installation in Kuwait. Protect your home from overloads.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نركب القواطع الرئيسية لحماية منزلك من الأحمال الزائدة والأعطال الكهربائية.</p><ul><li>قواطع معتمدة</li><li>تركيب احترافي</li><li>حماية فائقة</li></ul>', 'en' => '<p>We install main breakers to protect your home from overloads and electrical faults.</p><ul><li>Approved breakers</li><li>Professional installation</li><li>Superior protection</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 4,
            ],
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'تبديل قاطع كهرباء الكويت', 'en' => 'Circuit Breaker Replacement Kuwait'],
                'slug'        => ['ar' => 'تبديل-قاطع-كهرباء-الكويت', 'en' => 'circuit-breaker-replacement-kuwait'],
                'meta_title'  => ['ar' => 'تبديل قاطع كهرباء الكويت | إلكتريك كويت', 'en' => 'Circuit Breaker Replacement Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تبديل القواطع الكهربائية التالفة في الكويت. استبدال سريع وآمن.', 'en' => 'Replacement of damaged circuit breakers in Kuwait. Fast and safe replacement.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نستبدل القواطع الكهربائية التالفة أو القديمة بقواطع حديثة موثوقة.</p><ul><li>قواطع أصلية</li><li>تركيب سريع</li><li>ضمان سنة</li></ul>', 'en' => '<p>We replace damaged or old circuit breakers with modern reliable ones.</p><ul><li>Original breakers</li><li>Fast installation</li><li>One-year warranty</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 5,
            ],
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'تركيب RCCB الكويت', 'en' => 'RCCB Installation Kuwait'],
                'slug'        => ['ar' => 'تركيب-rccb-الكويت', 'en' => 'rccb-installation-kuwait'],
                'meta_title'  => ['ar' => 'تركيب RCCB الكويت | إلكتريك كويت', 'en' => 'RCCB Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب قاطع RCCB للحماية من الصدمات الكهربائية في الكويت. سلامة قصوى.', 'en' => 'RCCB installation for protection from electric shocks in Kuwait. Maximum safety.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نركب قواطع RCCB لحماية أفراد الأسرة من خطر الصدمات الكهربائية.</p><ul><li>حماية فورية</li><li>معايير أوروبية</li><li>تركيب احترافي</li></ul>', 'en' => '<p>We install RCCB breakers to protect family members from electric shock hazards.</p><ul><li>Instant protection</li><li>European standards</li><li>Professional installation</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 6,
            ],
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'تركيب MCB الكويت', 'en' => 'MCB Installation Kuwait'],
                'slug'        => ['ar' => 'تركيب-mcb-الكويت', 'en' => 'mcb-installation-kuwait'],
                'meta_title'  => ['ar' => 'تركيب MCB الكويت | إلكتريك كويت', 'en' => 'MCB Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب قواطع MCB في الكويت. حماية دوائرك الكهربائية من الأحمال الزائدة.', 'en' => 'MCB installation in Kuwait. Protect your electrical circuits from overloads.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نركب قواطع MCB لحماية الدوائر الكهربائية من الأحمال الزائدة والقصر.</p><ul><li>قواطع أصلية</li><li>توزيع صحيح</li><li>حماية الدوائر</li></ul>', 'en' => '<p>We install MCB breakers to protect electrical circuits from overloads and short circuits.</p><ul><li>Original breakers</li><li>Correct distribution</li><li>Circuit protection</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 7,
            ],
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'فحص لوحة كهربائية منزلية الكويت', 'en' => 'Home Electrical Panel Inspection Kuwait'],
                'slug'        => ['ar' => 'فحص-لوحة-كهربائية-منزلية-الكويت', 'en' => 'home-electrical-panel-inspection-kuwait'],
                'meta_title'  => ['ar' => 'فحص لوحة كهربائية منزلية الكويت | إلكتريك كويت', 'en' => 'Home Electrical Panel Inspection Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'فحص شامل للوحة الكهربائية المنزلية في الكويت. اكتشف المشاكل قبل وقوعها.', 'en' => 'Comprehensive home electrical panel inspection in Kuwait. Detect problems before they occur.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم فحصاً شاملاً للوحة الكهربائية في منزلك لضمان سلامة وكفاءة النظام.</p><ul><li>فحص القواطع</li><li>إحكام التوصيلات</li><li>تقرير مفصل</li></ul>', 'en' => '<p>We provide a comprehensive inspection of your home electrical panel to ensure system safety and efficiency.</p><ul><li>Breaker inspection</li><li>Connection tightening</li><li>Detailed report</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 8,
            ],
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'القاطع الرئيسي يفصل الكويت', 'en' => 'Main Breaker Keeps Tripping Kuwait'],
                'slug'        => ['ar' => 'القاطع-الرئيسي-يفصل-الكويت', 'en' => 'main-breaker-tripping-kuwait'],
                'meta_title'  => ['ar' => 'القاطع الرئيسي يفصل الكويت | إلكتريك كويت', 'en' => 'Main Breaker Keeps Tripping Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'القاطع الرئيسي يفصل باستمرار؟ نحل المشكلة بسرعة في الكويت.', 'en' => 'Main breaker keeps tripping? We solve the problem quickly in Kuwait.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نشخص ونحل مشكلة القاطع الرئيسي الذي يفصل باستمرار لحماية منزلك.</p><ul><li>تشخيص السبب</li><li>إصلاح فوري</li><li>منع التكرار</li></ul>', 'en' => '<p>We diagnose and solve the main breaker tripping issue to protect your home.</p><ul><li>Cause diagnosis</li><li>Immediate repair</li><li>Prevention of recurrence</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 9,
            ],
            [
                'pillar_slug' => 'electrical-panels-circuit-breakers-kuwait',
                'title'       => ['ar' => 'توزيع الأحمال الكهربائية الكويت', 'en' => 'Electrical Load Distribution Kuwait'],
                'slug'        => ['ar' => 'توزيع-الأحمال-الكهربائية-الكويت', 'en' => 'electrical-load-distribution-kuwait'],
                'meta_title'  => ['ar' => 'توزيع الأحمال الكهربائية الكويت | إلكتريك كويت', 'en' => 'Electrical Load Distribution Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'توزيع الأحمال الكهربائية بشكل صحيح في الكويت لتحسين الأداء ومنع الأعطال.', 'en' => 'Proper electrical load distribution in Kuwait to improve performance and prevent faults.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نوزع الأحمال الكهربائية بشكل صحيح لتحسين أداء النظام ومنع الأعطال.</p><ul><li>قياس الأحمال الحالية</li><li>إعادة التوزيع</li><li>تحسين الكفاءة</li></ul>', 'en' => '<p>We distribute electrical loads properly to improve system performance and prevent faults.</p><ul><li>Current load measurement</li><li>Redistribution</li><li>Efficiency improvement</li></ul>'],
                'search_intent' => 'informational',
                'status'      => 'active',
                'sort_order'  => 10,
            ],

            // ── Pillar 5: lighting-spotlight-installation-kuwait ──────────
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'تركيب سبوت لايت الكويت', 'en' => 'Spotlight Installation Kuwait'],
                'slug'        => ['ar' => 'تركيب-سبوت-لايت-الكويت', 'en' => 'spotlight-installation-kuwait'],
                'meta_title'  => ['ar' => 'تركيب سبوت لايت الكويت | إلكتريك كويت', 'en' => 'Spotlight Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب سبوت لايت في الكويت. إضاءة احترافية للمنازل والمكاتب بأسعار مناسبة.', 'en' => 'Spotlight installation in Kuwait. Professional lighting for homes and offices at competitive prices.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نركب السبوت لايت في منزلك بأعلى معايير الجودة والجمال.</p><ul><li>تنسيق احترافي</li><li>إضاءة متوازنة</li><li>أسعار مناسبة</li></ul>', 'en' => '<p>We install spotlights in your home to the highest quality and aesthetic standards.</p><ul><li>Professional coordination</li><li>Balanced lighting</li><li>Competitive prices</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 1,
            ],
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'تركيب ثريات الكويت', 'en' => 'Chandelier Installation Kuwait'],
                'slug'        => ['ar' => 'تركيب-ثريات-الكويت', 'en' => 'chandelier-installation-kuwait'],
                'meta_title'  => ['ar' => 'تركيب ثريات الكويت | إلكتريك كويت', 'en' => 'Chandelier Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب الثريات في الكويت باحترافية وأمان. فنيون متخصصون في الإضاءة.', 'en' => 'Professional and safe chandelier installation in Kuwait. Lighting specialists.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نركب الثريات بأنواعها المختلفة بأمان واحترافية في الكويت.</p><ul><li>تركيب آمن</li><li>توصيل احترافي</li><li>ضمان على العمل</li></ul>', 'en' => '<p>We install all types of chandeliers safely and professionally in Kuwait.</p><ul><li>Safe installation</li><li>Professional connection</li><li>Work warranty</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 2,
            ],
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'تركيب إضاءة LED الكويت', 'en' => 'LED Lighting Installation Kuwait'],
                'slug'        => ['ar' => 'تركيب-إضاءة-led-الكويت', 'en' => 'led-lighting-installation-kuwait'],
                'meta_title'  => ['ar' => 'تركيب إضاءة LED الكويت | إلكتريك كويت', 'en' => 'LED Lighting Installation Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب إضاءة LED موفرة للطاقة في الكويت. خفض فاتورة الكهرباء.', 'en' => 'Energy-saving LED lighting installation in Kuwait. Reduce your electricity bill.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نركب أنظمة الإضاءة LED الموفرة للطاقة لخفض فاتورة كهربائك.</p><ul><li>توفير 70% من الطاقة</li><li>عمر افتراضي طويل</li><li>إضاءة ممتازة</li></ul>', 'en' => '<p>We install energy-saving LED lighting systems to reduce your electricity bill.</p><ul><li>70% energy saving</li><li>Long lifespan</li><li>Excellent lighting</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 3,
            ],
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'إضاءة مخفية الكويت', 'en' => 'Hidden Lighting Kuwait'],
                'slug'        => ['ar' => 'إضاءة-مخفية-الكويت', 'en' => 'hidden-lighting-kuwait'],
                'meta_title'  => ['ar' => 'إضاءة مخفية الكويت | إلكتريك كويت', 'en' => 'Hidden Lighting Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب الإضاءة المخفية في الكويت للديكور الراقي. فنيون متخصصون.', 'en' => 'Hidden lighting installation in Kuwait for elegant decor. Specialized technicians.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نتخصص في تركيب الإضاءة المخفية لإضفاء جمالية راقية على منزلك.</p><ul><li>تصميم احترافي</li><li>إضاءة ناعمة</li><li>ديكور راقٍ</li></ul>', 'en' => '<p>We specialize in installing hidden lighting to add elegant aesthetics to your home.</p><ul><li>Professional design</li><li>Soft lighting</li><li>Elegant decor</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 4,
            ],
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'إضاءة حدائق الكويت', 'en' => 'Garden Lighting Kuwait'],
                'slug'        => ['ar' => 'إضاءة-حدائق-الكويت', 'en' => 'garden-lighting-kuwait'],
                'meta_title'  => ['ar' => 'إضاءة حدائق الكويت | إلكتريك كويت', 'en' => 'Garden Lighting Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تصميم وتركيب إضاءة حدائق في الكويت. جمال ليلي لحديقتك.', 'en' => 'Garden lighting design and installation in Kuwait. Nighttime beauty for your garden.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نصمم ونركب إضاءة الحدائق لإضفاء جمال ليلي على منزلك في الكويت.</p><ul><li>تصميم مخصص</li><li>مقاومة للمناخ</li><li>أنظمة ذكية</li></ul>', 'en' => '<p>We design and install garden lighting to add nighttime beauty to your home in Kuwait.</p><ul><li>Custom design</li><li>Climate resistant</li><li>Smart systems</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 5,
            ],
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'إنارة خارجية فلل الكويت', 'en' => 'Villa Outdoor Lighting Kuwait'],
                'slug'        => ['ar' => 'إنارة-خارجية-فلل-الكويت', 'en' => 'villa-outdoor-lighting-kuwait'],
                'meta_title'  => ['ar' => 'إنارة خارجية فلل الكويت | إلكتريك كويت', 'en' => 'Villa Outdoor Lighting Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب إنارة خارجية للفلل في الكويت. إضاءة أمنية وجمالية معاً.', 'en' => 'Outdoor lighting installation for villas in Kuwait. Security and aesthetic lighting combined.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نركب إنارة خارجية للفلل توفر الأمان والجمال في آن واحد.</p><ul><li>إنارة أمنية</li><li>تصميم جمالي</li><li>مقاومة للطقس</li></ul>', 'en' => '<p>We install outdoor lighting for villas that provides both security and aesthetics.</p><ul><li>Security lighting</li><li>Aesthetic design</li><li>Weather resistant</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 6,
            ],
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'إنارة مجالس الكويت', 'en' => 'Majlis Lighting Kuwait'],
                'slug'        => ['ar' => 'إنارة-مجالس-الكويت', 'en' => 'majlis-lighting-kuwait'],
                'meta_title'  => ['ar' => 'إنارة مجالس الكويت | إلكتريك كويت', 'en' => 'Majlis Lighting Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'إنارة مجالس راقية في الكويت. تصميم يجمع الأصالة والحداثة.', 'en' => 'Elegant majlis lighting in Kuwait. Design combining tradition and modernity.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نصمم إنارة المجالس الكويتية بأسلوب يجمع الأصالة والحداثة.</p><ul><li>تصميم مخصص</li><li>إضاءة دافئة</li><li>أجواء مميزة</li></ul>', 'en' => '<p>We design majlis lighting that combines traditional and modern Kuwaiti style.</p><ul><li>Custom design</li><li>Warm lighting</li><li>Distinctive atmosphere</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 7,
            ],
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'صيانة الإنارة الكويت', 'en' => 'Lighting Maintenance Kuwait'],
                'slug'        => ['ar' => 'صيانة-الإنارة-الكويت', 'en' => 'lighting-maintenance-kuwait'],
                'meta_title'  => ['ar' => 'صيانة الإنارة الكويت | إلكتريك كويت', 'en' => 'Lighting Maintenance Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'صيانة أنظمة الإنارة في الكويت. إصلاح وتبديل المصابيح والتركيبات.', 'en' => 'Lighting system maintenance in Kuwait. Repair and replacement of lamps and fixtures.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم خدمات صيانة كاملة لأنظمة الإنارة في الكويت لضمان الأداء الأمثل.</p><ul><li>استبدال المصابيح</li><li>إصلاح الأعطال</li><li>صيانة دورية</li></ul>', 'en' => '<p>We provide complete maintenance services for lighting systems in Kuwait to ensure optimal performance.</p><ul><li>Lamp replacement</li><li>Fault repair</li><li>Periodic maintenance</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 8,
            ],
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'أفضل إنارة موفرة للطاقة الكويت', 'en' => 'Best Energy Saving Lighting Kuwait'],
                'slug'        => ['ar' => 'أفضل-إنارة-موفرة-للطاقة-الكويت', 'en' => 'best-energy-saving-lighting-kuwait'],
                'meta_title'  => ['ar' => 'أفضل إنارة موفرة للطاقة الكويت | إلكتريك كويت', 'en' => 'Best Energy Saving Lighting Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'اختر أفضل أنظمة الإنارة الموفرة للطاقة في الكويت. خبراء في الإضاءة الذكية.', 'en' => 'Choose the best energy-saving lighting systems in Kuwait. Smart lighting experts.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نساعدك في اختيار وتركيب أفضل أنظمة الإنارة الموفرة للطاقة في الكويت.</p><ul><li>استشارة مجانية</li><li>اختيار مثالي</li><li>توفير في الفاتورة</li></ul>', 'en' => '<p>We help you choose and install the best energy-saving lighting systems in Kuwait.</p><ul><li>Free consultation</li><li>Optimal selection</li><li>Bill savings</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 9,
            ],
            [
                'pillar_slug' => 'lighting-spotlight-installation-kuwait',
                'title'       => ['ar' => 'استبدال الإنارة القديمة الكويت', 'en' => 'Old Lighting Replacement Kuwait'],
                'slug'        => ['ar' => 'استبدال-الإنارة-القديمة-الكويت', 'en' => 'old-lighting-replacement-kuwait'],
                'meta_title'  => ['ar' => 'استبدال الإنارة القديمة الكويت | إلكتريك كويت', 'en' => 'Old Lighting Replacement Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'استبدال أنظمة الإنارة القديمة بأنظمة حديثة في الكويت. توفير في الطاقة والتكلفة.', 'en' => 'Replace old lighting systems with modern ones in Kuwait. Energy and cost savings.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نستبدل أنظمة الإنارة القديمة بأنظمة حديثة موفرة للطاقة وأكثر جمالاً.</p><ul><li>استشارة مجانية</li><li>استبدال احترافي</li><li>توفير فوري</li></ul>', 'en' => '<p>We replace old lighting systems with modern, energy-saving, and more aesthetic ones.</p><ul><li>Free consultation</li><li>Professional replacement</li><li>Immediate savings</li></ul>'],
                'search_intent' => 'transactional',
                'status'      => 'active',
                'sort_order'  => 10,
            ],

            // ── Pillar 6: electrician-villas-companies-kuwait ─────────────
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'كهربائي شركات الكويت', 'en' => 'Company Electrician Kuwait'],
                'slug'        => ['ar' => 'كهربائي-شركات-الكويت', 'en' => 'company-electrician-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي شركات الكويت | إلكتريك كويت', 'en' => 'Company Electrician Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'خدمات كهربائية متكاملة للشركات في الكويت. صيانة وتركيب باحترافية.', 'en' => 'Complete electrical services for companies in Kuwait. Professional maintenance and installation.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم خدمات كهربائية متكاملة للشركات والمنشآت التجارية في الكويت.</p><ul><li>فريق متخصص</li><li>خدمة موثوقة</li><li>عقود مرنة</li></ul>', 'en' => '<p>We provide complete electrical services for companies and commercial establishments in Kuwait.</p><ul><li>Specialized team</li><li>Reliable service</li><li>Flexible contracts</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 1,
            ],
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'كهربائي مكاتب الكويت', 'en' => 'Office Electrician Kuwait'],
                'slug'        => ['ar' => 'كهربائي-مكاتب-الكويت', 'en' => 'office-electrician-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي مكاتب الكويت | إلكتريك كويت', 'en' => 'Office Electrician Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'خدمات كهربائية للمكاتب والمباني التجارية في الكويت. صيانة وتأسيس.', 'en' => 'Electrical services for offices and commercial buildings in Kuwait. Maintenance and installation.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نتخصص في الأعمال الكهربائية للمكاتب والمباني التجارية في الكويت.</p><ul><li>تأسيس المكاتب</li><li>صيانة دورية</li><li>أعمال نظيفة</li></ul>', 'en' => '<p>We specialize in electrical work for offices and commercial buildings in Kuwait.</p><ul><li>Office installation</li><li>Periodic maintenance</li><li>Clean work</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 2,
            ],
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'كهربائي محلات تجارية الكويت', 'en' => 'Shop Electrician Kuwait'],
                'slug'        => ['ar' => 'كهربائي-محلات-تجارية-الكويت', 'en' => 'shop-electrician-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي محلات تجارية الكويت | إلكتريك كويت', 'en' => 'Shop Electrician Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تأسيس وصيانة الكهرباء للمحلات التجارية في الكويت. سرعة وجودة.', 'en' => 'Electrical installation and maintenance for shops in Kuwait. Speed and quality.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقوم بتأسيس وصيانة كهرباء المحلات التجارية في الكويت بأعلى معايير الجودة.</p><ul><li>تأسيس سريع</li><li>صيانة موثوقة</li><li>أسعار تنافسية</li></ul>', 'en' => '<p>We install and maintain electrical systems for shops in Kuwait to the highest quality standards.</p><ul><li>Fast installation</li><li>Reliable maintenance</li><li>Competitive prices</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 3,
            ],
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'كهربائي مستودعات الكويت', 'en' => 'Warehouse Electrician Kuwait'],
                'slug'        => ['ar' => 'كهربائي-مستودعات-الكويت', 'en' => 'warehouse-electrician-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي مستودعات الكويت | إلكتريك كويت', 'en' => 'Warehouse Electrician Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'خدمات كهربائية للمستودعات والمخازن في الكويت. تأسيس وصيانة باحترافية.', 'en' => 'Electrical services for warehouses and storage facilities in Kuwait. Professional installation and maintenance.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم خدمات كهربائية متكاملة للمستودعات والمخازن في الكويت.</p><ul><li>أنظمة إنارة صناعية</li><li>لوحات كهربائية</li><li>صيانة دورية</li></ul>', 'en' => '<p>We provide complete electrical services for warehouses and storage facilities in Kuwait.</p><ul><li>Industrial lighting systems</li><li>Electrical panels</li><li>Periodic maintenance</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 4,
            ],
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'كهربائي مصانع الكويت', 'en' => 'Factory Electrician Kuwait'],
                'slug'        => ['ar' => 'كهربائي-مصانع-الكويت', 'en' => 'factory-electrician-kuwait'],
                'meta_title'  => ['ar' => 'كهربائي مصانع الكويت | إلكتريك كويت', 'en' => 'Factory Electrician Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'خدمات كهربائية للمصانع والمنشآت الصناعية في الكويت. فريق متخصص.', 'en' => 'Electrical services for factories and industrial facilities in Kuwait. Specialized team.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نتخصص في الأعمال الكهربائية للمصانع والمنشآت الصناعية في الكويت.</p><ul><li>أنظمة صناعية</li><li>ثلاث فاز</li><li>فريق متخصص</li></ul>', 'en' => '<p>We specialize in electrical work for factories and industrial facilities in Kuwait.</p><ul><li>Industrial systems</li><li>Three-phase</li><li>Specialized team</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 5,
            ],
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'صيانة كهرباء الشركات الكويت', 'en' => 'Company Electrical Maintenance Kuwait'],
                'slug'        => ['ar' => 'صيانة-كهرباء-الشركات-الكويت', 'en' => 'company-electrical-maintenance-kuwait'],
                'meta_title'  => ['ar' => 'صيانة كهرباء الشركات الكويت | إلكتريك كويت', 'en' => 'Company Electrical Maintenance Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'صيانة كهرباء الشركات والمنشآت التجارية في الكويت. عقود صيانة مرنة.', 'en' => 'Electrical maintenance for companies and commercial establishments in Kuwait. Flexible maintenance contracts.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم عقود صيانة كهربائية للشركات والمنشآت في الكويت لضمان استمرارية العمل.</p><ul><li>صيانة دورية</li><li>استجابة طارئة</li><li>عقود مرنة</li></ul>', 'en' => '<p>We provide electrical maintenance contracts for companies and establishments in Kuwait to ensure business continuity.</p><ul><li>Periodic maintenance</li><li>Emergency response</li><li>Flexible contracts</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 6,
            ],
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'تمديد كهرباء تجارية الكويت', 'en' => 'Commercial Electrical Wiring Kuwait'],
                'slug'        => ['ar' => 'تمديد-كهرباء-تجارية-الكويت', 'en' => 'commercial-electrical-wiring-kuwait'],
                'meta_title'  => ['ar' => 'تمديد كهرباء تجارية الكويت | إلكتريك كويت', 'en' => 'Commercial Electrical Wiring Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تمديد الكهرباء للمنشآت التجارية في الكويت. أعمال احترافية وفق المواصفات.', 'en' => 'Commercial electrical wiring in Kuwait. Professional work according to specifications.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نمدد الكهرباء للمنشآت التجارية وفق أعلى المواصفات الكويتية والدولية.</p><ul><li>مواصفات معتمدة</li><li>فريق محترف</li><li>ضمان شامل</li></ul>', 'en' => '<p>We wire commercial establishments according to the highest Kuwaiti and international specifications.</p><ul><li>Approved specifications</li><li>Professional team</li><li>Comprehensive warranty</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 7,
            ],
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'لوحات كهربائية صناعية الكويت', 'en' => 'Industrial Electrical Panels Kuwait'],
                'slug'        => ['ar' => 'لوحات-كهربائية-صناعية-الكويت', 'en' => 'industrial-electrical-panels-kuwait'],
                'meta_title'  => ['ar' => 'لوحات كهربائية صناعية الكويت | إلكتريك كويت', 'en' => 'Industrial Electrical Panels Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'تركيب وصيانة اللوحات الكهربائية الصناعية في الكويت. خبرة واسعة.', 'en' => 'Installation and maintenance of industrial electrical panels in Kuwait. Wide experience.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نتخصص في تركيب وصيانة اللوحات الكهربائية الصناعية للمصانع والمنشآت.</p><ul><li>لوحات صناعية معتمدة</li><li>تركيب متخصص</li><li>صيانة دورية</li></ul>', 'en' => '<p>We specialize in the installation and maintenance of industrial electrical panels for factories and establishments.</p><ul><li>Approved industrial panels</li><li>Specialized installation</li><li>Periodic maintenance</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 8,
            ],
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'صيانة المجمعات التجارية الكويت', 'en' => 'Commercial Complex Maintenance Kuwait'],
                'slug'        => ['ar' => 'صيانة-المجمعات-التجارية-الكويت', 'en' => 'commercial-complex-maintenance-kuwait'],
                'meta_title'  => ['ar' => 'صيانة المجمعات التجارية الكويت | إلكتريك كويت', 'en' => 'Commercial Complex Maintenance Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'صيانة الكهرباء في المجمعات التجارية بالكويت. فرق متخصصة ومرنة.', 'en' => 'Electrical maintenance in commercial complexes in Kuwait. Specialized and flexible teams.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم خدمات صيانة كهربائية متكاملة للمجمعات التجارية في الكويت.</p><ul><li>فرق متخصصة</li><li>صيانة شاملة</li><li>استجابة سريعة</li></ul>', 'en' => '<p>We provide complete electrical maintenance services for commercial complexes in Kuwait.</p><ul><li>Specialized teams</li><li>Comprehensive maintenance</li><li>Fast response</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 9,
            ],
            [
                'pillar_slug' => 'electrician-villas-companies-kuwait',
                'title'       => ['ar' => 'عقود صيانة كهربائية للشركات الكويت', 'en' => 'Electrical Maintenance Contracts Companies Kuwait'],
                'slug'        => ['ar' => 'عقود-صيانة-كهربائية-للشركات-الكويت', 'en' => 'electrical-maintenance-contracts-companies-kuwait'],
                'meta_title'  => ['ar' => 'عقود صيانة كهربائية للشركات الكويت | إلكتريك كويت', 'en' => 'Electrical Maintenance Contracts Companies Kuwait | ElectricQ8'],
                'meta_description' => ['ar' => 'عقود صيانة كهربائية سنوية للشركات في الكويت. أسعار تنافسية وخدمة موثوقة.', 'en' => 'Annual electrical maintenance contracts for companies in Kuwait. Competitive prices and reliable service.'],
                'canonical_url' => ['ar' => '', 'en' => ''],
                'content'     => ['ar' => '<p>نقدم عقود صيانة كهربائية سنوية للشركات بأسعار تنافسية وخدمة موثوقة.</p><ul><li>عقود سنوية</li><li>صيانة شاملة</li><li>أولوية في الاستجابة</li></ul>', 'en' => '<p>We offer annual electrical maintenance contracts for companies at competitive prices with reliable service.</p><ul><li>Annual contracts</li><li>Comprehensive maintenance</li><li>Priority response</li></ul>'],
                'search_intent' => 'commercial',
                'status'      => 'active',
                'sort_order'  => 10,
            ],
        ];

        foreach ($clusters as $data) {
            $pillarSlug = $data['pillar_slug'];
            unset($data['pillar_slug']);

            $pillar = Pillar::where('slug->en', $pillarSlug)->first();

            if (! $pillar) {
                $this->command->warn("Pillar not found: {$pillarSlug} — skipping.");
                continue;
            }

            $data['pillar_id'] = $pillar->id;
            $data['image_url'] = null;

            Cluster::create($data);
        }

        $this->command->info('ClusterSeeder: 60 clusters seeded successfully.');
    }
}
